#!/usr/bin/env python 

import rospy
from geometry_msgs.msg import Twist

def movement_pub():
    move_pub = rospy.Publisher("/turtle1/cmd_vel", Twist, queue_size = 10)
    rospy.init_node("move_node", anonymous=True)
    rate = rospy.Rate(10)
    move = Twist()
    while not rospy.is_shutdown():
        try:
            move.linear.x = 2
            move.angular.z = 0.6
            move_pub.publish(move)
            rospy.loginfo(str(move) + "yww")
        except rospy.ROSInternalException:
            pass
if __name__ == "__main__":
    movement_pub()
